# Generated by Django 2.0.6 on 2020-05-31 07:03

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(default='USER', max_length=250)),
                ('name', models.CharField(blank=True, max_length=250)),
                ('email', models.CharField(blank=True, max_length=250)),
                ('gender', models.CharField(blank=True, max_length=250)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('isActive', models.BooleanField(default=True)),
                ('houseNumber', models.CharField(blank=True, max_length=250)),
                ('street', models.CharField(blank=True, max_length=250)),
                ('addressLine', models.CharField(blank=True, max_length=250)),
                ('mobileNumber', models.CharField(blank=True, max_length=250)),
                ('country', models.CharField(default='India', max_length=250)),
                ('designation', models.CharField(blank=True, max_length=250)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('emp_id', models.CharField(max_length=250)),
                ('leave_type', models.CharField(max_length=250)),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=250)),
                ('posting_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('admin_remark', models.CharField(blank=True, max_length=250)),
                ('admin_remark_date', models.DateField(blank=True)),
                ('status', models.IntegerField(default=0)),
                ('is_read', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('createdOn', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created date')),
            ],
        ),
    ]
