# Generated by Django 2.2.12 on 2020-06-02 13:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('task_id', models.CharField(max_length=250)),
                ('username', models.CharField(max_length=250)),
                ('comment', models.CharField(max_length=500)),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
