# Generated by Django 2.0.6 on 2020-05-24 15:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.CharField(default='8cf888189dd211eab27b505bc2d0f560', max_length=250, primary_key=True, serialize=False)),
                ('emp_id', models.CharField(max_length=250)),
                ('leave_type', models.CharField(max_length=250)),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=250)),
                ('posting_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('admin_remark', models.CharField(blank=True, max_length=250)),
                ('admin_remark_date', models.DateField(blank=True)),
                ('status', models.IntegerField()),
                ('is_read', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='user_id',
            field=models.CharField(blank=True, default='8cf7ec829dd211ea8854505bc2d0f560', max_length=250, unique=True),
        ),
    ]
