# Generated by Django 2.2.12 on 2020-06-02 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_taskcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskcomment',
            old_name='data',
            new_name='date',
        ),
    ]
