# Generated by Django 2.0.6 on 2020-05-24 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200524_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='user_id',
            field=models.CharField(blank=True, default='48b5238a9dd411eaa4c6505bc2d0f560', max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='id',
            field=models.CharField(default='48bc23989dd411eabf1d505bc2d0f560', max_length=250, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='leave',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='leave',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
