# Generated by Django 2.2.12 on 2020-05-28 04:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200524_2106'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.CharField(default='ef01f194a09f11eabcaef4d108ccf735', max_length=250, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('createdOn', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created date')),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='user_id',
            field=models.CharField(blank=True, default='ef017a73a09f11ea93c9f4d108ccf735', max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='id',
            field=models.CharField(default='ef01f193a09f11ea85e5f4d108ccf735', max_length=250, primary_key=True, serialize=False),
        ),
    ]
