# Generated by Django 2.2.12 on 2020-06-03 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200602_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='isWorking',
            field=models.BooleanField(default=False),
        ),
    ]
