# Generated by Django 2.2.12 on 2020-05-28 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200528_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='user_id',
            field=models.CharField(blank=True, default='0251cf94a0b211eaba69f4d108ccf735', max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='id',
            field=models.CharField(default='02524488a0b211eaa542f4d108ccf735', max_length=250, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='id',
            field=models.CharField(max_length=250, primary_key=True, serialize=False),
        ),
    ]
