# Generated by Django 2.2.12 on 2020-05-29 11:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200528_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, max_length=250)),
                ('assignTo', models.TextField(blank=True, max_length=250)),
                ('status', models.IntegerField(default=0)),
                ('due', models.IntegerField(default=0)),
                ('createdOn', models.DateTimeField(default=django.utils.timezone.now)),
                ('deadline', models.DateField()),
                ('customer_id', models.CharField(max_length=250)),
                ('complete_percentage', models.FloatField(default=0.0)),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='user_id',
            field=models.CharField(blank=True, default='73e1180fa1a211ea8afef4d108ccf735', max_length=250, unique=True),
        ),
    ]
