# Generated by Django 2.2.12 on 2020-05-28 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200528_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='user_id',
            field=models.CharField(blank=True, default='3005e4d0a0c911eaba373148ae0171ab', max_length=250, unique=True),
        ),
    ]
