# Generated by Django 2.2.12 on 2020-05-28 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200528_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='user_id',
            field=models.CharField(blank=True, default='52f76ccaa0c911ea84d7e70709ba742c', max_length=250, unique=True),
        ),
    ]
