# Generated by Django 2.2.12 on 2020-05-29 12:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200529_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, max_length=250)),
                ('assignTo', models.TextField(blank=True, max_length=250)),
                ('project_id', models.CharField(max_length=250)),
                ('status', models.IntegerField(default=0)),
                ('due', models.IntegerField(default=0)),
                ('createdOn', models.DateTimeField(default=django.utils.timezone.now)),
                ('deadline', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='user_id',
            field=models.CharField(blank=True, default='afee41e0a1a611ea8acbf4d108ccf735', max_length=250, unique=True),
        ),
    ]
