# Generated by Django 2.2.12 on 2020-05-30 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200529_1749'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorksOn',
            fields=[
                ('id', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('project_id', models.CharField(max_length=250)),
                ('emp_id', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='user_id',
            field=models.CharField(blank=True, default='7cf09612a24211eaa422edfbab785d20', max_length=250, unique=True),
        ),
    ]
