# Generated by Django 2.2.12 on 2020-05-29 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200528_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='user_id',
            field=models.CharField(blank=True, default='43355caea16811eab73e5cea1d1d8722', max_length=250, unique=True),
        ),
    ]
